# Gradle Properties
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
# Multiplatform Settings
kotlin.mpp.enableCInteropCommonization=true
org.gradle.java.home=C\:\\Users\\yugik\\scoop\\apps\\openjdk22\\current
